# Generated by Django 6.0.5 on 2026-05-24 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=255)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'SCOPE_1'), ('SCOPE_2', 'SCOPE_2'), ('SCOPE_3', 'SCOPE_3')], max_length=50)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('co2e_emission', models.FloatField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('review_status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=50)),
                ('is_flagged', models.BooleanField(default=False)),
                ('locked_for_audit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='organizations.organization')),
                ('raw_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='ingestion.rawrecord')),
            ],
        ),
    ]
